#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ServoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
moveMotor(rightMotor, 5.0, seconds, 127/2);
moveMotor(leftMotor, 2.5, seconds, 3 * 127 / 4);
setMultipleMotors(127, rightMotor, leftMotor);
wait(7.25);

}
