#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

turnLEDOff(green);
wait(1);
turnLEDOn(green);
wait(1);
turnLEDOff(green);
wait(1);
turnLEDOn(green);
wait(1);
turnLEDOff(green);
//the LED turns off and then blinks on twice before turning off again



}
