#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           ServoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

//startMotor(rightMotor, 127/2);
//startMotor(leftMotor, 127/2);
startMotor(rightMotor, -127/2); //reversed rightMotor by setting speed to negation of original speed
startMotor(leftMotor, 127/2); //reversed leftMotor by configuring it to be reversed in the Motor and Sensor Setup
wait(5);
stopMotor(rightMotor);
stopMotor(leftMotor);



}
