#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ServoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
setServo(servoMotor, -127);
wait(2);
setServo(servoMotor, 0);
wait(2);
setServo(servoMotor, 127);
wait(2);

//the servo went to a starting (default) position that seems to be postion 0,
//waited 2 seconds,
//then rotated counter-clockwise a certain increment,
//waited 2 seconds,
//rotated counter-clockwise again the same increment,
//waited 2 seconds,
//and finally rotated clockwise once for the same increment (returning to the starting position).
}
