#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ServoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
setServo(servoMotor, -127);
wait(2);
setServo(servoMotor, -63);
wait(3);
setServo(servoMotor, 0);
wait(2);
setServo(servoMotor, 127);


}
